### ISSUE TITLE
Ability to output response in JSON

### ISSUE THREAD

**Issue by moozhub** [gbxyz/rdap-web-client#1]
Is there an ability to output the entire response for a domain request in JSON much like many of the other RDAP endpoints provide?

Eg. curl -H "Content-Type: application/json"  -X GET 'https://rdap.cloudflare.com/rdap/v1/domain/cloudflare.com'

**Comment by gbxyz** [comment]
You've submitted this issue on the repository for a web-based RDAP client. If you want to see the raw JSON of an RDAP record in your browser then just paste the URL into the address bar.

Or did you mean to submit this issue on the [rdapper](https://github.com/gbxyz/rdapper/issues) issue tracker? That is a command-line RDAP client, which has the `--raw` option to display the raw JSON.

**Comment by moozhub** [comment]
No, you answered my question. Thanks. For some reason I apparently was originally GETing the data from the client.rdap.org domain in my tests (oddly, even though I posted an example with curl of the URL you gave me in your answer, I apparently didn't actually try it). Issue can be closed, thanks for your time.
